Counter 앱 구현 완료
CodeSoom/week2-assignment-1 pull request #27
Opened 2020-09-21 01:12 UTC by dongakim

Counter 컴포넌트를 생성하고
Counter 컴포넌트의 구성요소인 CounterButton, CounterButtonWithNumber 컴포넌트를
생성함.

2020-09-21 16:04 UTC, Kihyun92 requested changes
좋은 고민을 해보신 것 같습니다~ 어떤 면에서 children으로 해당 내용을 받는게 더 좋을지 생각해보시면 금방 답을 찾으실 것 같네요! 잘 모르겠다면 둘 다 구현해보는것도 괜찮겠네요 :)

이번 과제의 의도를 한번 생각해보셨으면 좋겠습니다~ 그리고 아샬님의 강의를 빠르게 복습해보면서 아샬님이 왜 함수들을 어떻게 분리 했는지 파악해보시면 좋겠네요! ☺️

2020-09-21 16:04 UTC, Kihyun92 commented on src/CounterButtonWithNumber.jsx
> +function CounterButtonWithNumber({
함수 네이밍에 대해서 고민을 많이 하신 것 같네요~👍 간결하고 명확한 네이밍! 참 어렵죠..

일단 이 함수는 counter 컴포넌트 아래에 있는 숫자가 입력된 버튼입니다. 이미 Counter 컴포넌트에 종속되어 있기 대문에 CounterButton~~과 같이 앞에 counter라고 명시할 필요는 없어보입니다.

그리고 한번 이번 과제의 의도인 `관심사의 분리 관점`에서 이 컴포넌트를 안과 밖에서 봤을때 어떤 네이밍이면 괜찮을지 고민해보셔도 좋을 것 같습니다~

2020-09-22 14:41 UTC, Kihyun92 requested changes
버튼 컴포넌트를 재사용 하는 관점에서 많이 고민해보신 것 같습니다.👍 이번 과제의 의도 관점에서 한번 더 고민해보시면 좋을 것 같아요~

2020-09-22 14:41 UTC, Kihyun92 commented on src/App.jsx
> +  };
handleClick은 단순히 값만 넘겨주고 있네요! 하나의 함수로 합칠 수 있지 않을까요?

2020-09-22 14:41 UTC, Kihyun92 commented on src/Button.jsx
> +}
버튼을 공통으로 사용하기위해 많은 고민을 하신것 같아요!👍

하지만, 이번 과제의 의도에서 생각해보면 일단 이 컴포넌트에는 하나의 관심사만 있는게 아닌 것 같아요~
일단 children 여부로 화면 노출 여부를 판단하는 자체가 제어문이 들어간 것이고, 그로 인해 컴포넌트 복잡도가 올라가게되어 동료들이 명확하게 이해하기 어려운 코드가 된 것 같습니다.

`비용`이라는 부분에서 고민을 해보시면 좋을 것 같아요.
재사용성을 위해 복잡도가 약간있지만 컴포넌트의 수를 줄일건지, 혹은 이해하기 쉬운 컴포넌트 여러개를 만들지 같이요 ㅎㅎ
컴포넌트의 양도 비용이 되고, 코드를 해석하는데 드는 노력도 비용이라 볼 수 있을 것 같네요

2020-09-22 14:41 UTC, Kihyun92 commented on src/Buttons.jsx
> +      </Button>
key 값 추가가 필요해보입니다!
참고: https://reactjs.org/docs/lists-and-keys.html

그리고 value를 따로 넘기지 않고 처리 할 방법은 없을까요? Button 컴포넌트에서 따로 처리할 필요 없이요 :)

2020-09-23 13:37 UTC, kimkhyun requested changes
과제의 의도를 이해하신 것 같네요! :) 아마 마지막 피드백이 될 것 같네요~ 👍

2020-09-23 13:37 UTC, kimkhyun commented on src/App.jsx
> +  };
공통 로직을 잘 추출 하셨네요!! 좋습니다. 이 경우에 handleClickButton 과 handleClickButtons 이 어떤 역할을 하고있나요? updateCount를 props로 넘겨주면 어떻게 될까요?

2020-09-23 13:47 UTC, Kihyun92 requested changes

2020-09-24 09:14 UTC, dongakim commented on src/App.jsx
> +  };
네. updateCount를 props로 바로 넘겨주고
매핑하는 handle메서드를 제거하면 App 컴포넌트가 더 깔끔해지겠네요!

2020-09-24 14:06 UTC, Kihyun92 approved these changes
좋습니다~ 이번 과제를 통해 어떤걸 배우셨는지 한번 돌아보면 좋겠습니다:)

2020-10-05 12:57 UTC, merged