Counter 앱 만들고 파일 분리하기
CodeSoom/week2-assignment-1 pull request #28
Opened 2020-09-21 02:28 UTC by bbhye1

### **구현내용**

- [ ] - Click me를 누르면 숫자가 1씩 증가한다.
- [ ] - 숫자버튼을 누르면 숫자가  해당 숫자만큼 증가한다.
- [ ] - 컴포넌트 파일들을 분리한다. 

### **제한조건**

- [ ] - switch, else, let사용 불가
- [ ] - 함수이름과 변수이름을 줄이지 않고 사용 
- [ ] - indent(들여쓰기) depth를 1로 유지

2020-09-21 06:41 UTC, bbhye1 commented
### **중간 구현 내용**

처음은 강의에서 배운대로 구성을 해주었고 숫자버튼을 누르면 해당 숫자만큼 증가하도록 HandleClick 함수의 변경될 count값을
조정해 주었습니다. 
 또 각각의 역할이 다르다고 생각하는 컴포넌트들을 모두 분리시켜주었습니다. 이 작업을 마치고 나니 Counter의 기능이 다른 Button들과 다르지 않고 단지 버튼 안에 들어가는 텍스트만 다를 뿐이라 Button을 재사용해도 되겠다고 생각했고 리팩토링 해주었습니다. 
리팩토링 과정에서 최대한 원래 내용을 건드리지 않고 내용을 추가하여 테스트했습니다. 
짧은 리팩토링이지만 혹시 더 보완할 점이 있다면 조언 부탁드립니다!

2020-09-21 16:19 UTC, Kihyun92 requested changes
전반적으로 과제의 의도를 파악하신 것 같습니다~ 강의 영상도 잘 봐주신 것 같구요. 

재사용 가능하게 만들어진 버튼 컴포넌트를 다양한 곳에서 사용할 수 없을지 고민하시는 모습 좋네요 👍

2020-09-21 16:19 UTC, Kihyun92 commented on src/App.jsx
> +  function handleClick(number) {
좋습니다! 개인적으로 number라는 매개변수로는 이 handleClick의 역할을 알기 어려운 것 같습니다. 더 좋은 단어가 없을까요? 🤔

2020-09-21 16:19 UTC, Kihyun92 commented on src/Counter.jsx
> +    </Button>
좋은 고민인 것 같습니다~👍

이 경우에는 답은 없는 것 같아요 ㅎㅎ 다만, Button 컴포넌트를 만든 목적이 뭔지 한번 생각해보시면 좋을 것 같습니다~

지금은 스타일이 고려되지 않았지만, 만약 숫자 버튼들에만 적용되는 스타일이 있다면 어떻게 될까요?

2020-09-22 00:45 UTC, bbhye1 commented on src/Counter.jsx
> +    </Button>
각자 다른 스타일이 적용되었다면 클래스로 다른 버튼을과 구분을 지어주는 방법으로 해결이 가능할거라고 생각합니다. 
DOM을 이루고 있는 컴포넌트들이 많아지면 다른 버튼(들)의 군집을 나누어 주는 게 클래스를 적용할때 불가피하겠네요. 이게 상위 컴포넌트가 필요한 이유이군요!! 깨달음을 얻습니다 ㅎㅎ

2020-09-22 01:26 UTC, bbhye1 commented
지금 하는 코드가 간단하고 짧은 코드라 컴포넌트들 왜 묶어야 하는 지 잘 안 와닿았는데 여러 컴포넌트들이 복잡하게 얽혀있고 각각 다른 스타일과 기능을 한다면 이라는 생각을 하니 왜 필요한지에 대한 의문이 하나씩 해소됩니다. 역시 뭐든 큰그림이 중요한가봅니다 ㅎㅎㅎ.  

 여기 현재로는 다른 클릭하는 핸들러가 없어서 handleClick함수의 이름을 바꿔주기 보다는 들어오는 파라미터의 이름을 구체화해서 increasingNumber(증가 수)로 변경해주었습니다.

2020-09-22 14:56 UTC, Kihyun92 requested changes
좋습니다~ 제가 드린 피드백보다 더 많은걸 스스로 배우시는것 같아요 ☺️

2020-09-22 14:56 UTC, Kihyun92 commented on src/App.jsx
> +import Page from './Page';
```suggestion
import React, { useState } from 'react';

import Page from './Page';
```
한 줄 공백을 주시면 좋을 것 같습니다! 지금은 모듈이 별로 없지만, 모듈 간에도 역할이 있고, 분리를 해두는 습관을 두면 좋을 것 같아요 💯 
다른 파일들도 적용해주세요~

2020-09-23 00:33 UTC, bbhye1 commented on src/App.jsx
> +import Page from './Page';
변경 완료했습니다. 이제부터 습관을 잘 들여놓고 얼른 긴코드를 다룰만큼 실력이 늘어서 이 습관이 뿌듯해지는 순간이 왔으면 좋겠습니다 감사합니다! :):)

2020-09-24 14:08 UTC, Kihyun92 approved these changes
이번 과제를 하면서 어떤 생각을 해보았는지 한번 돌아보는것도 좋을 것 같습니다~ :)

2020-09-24 15:12 UTC, bbhye1 commented
### **완료 후 회고**

과제할때 중점으로 둔 점은 바로 컴포넌트들의 관심사 분리와 재사용성이었습니다. 얼마나 잘 나누어서 적재적소에 잘 사용할 수 있는 컴포넌트로 만드는가를 생각하면서 코드를 짰습니다. 버튼과 같은 컴포넌트는 onClick함수와 버튼태그 내부의 내용만 바뀐다면 어디든 맘껏 재사용이 가능한 컴포넌트라 버튼을 하드코딩하기 보다는 하나의 컴포넌트로 만들어 사용하는것이 리액트를 더 잘 활용하는 방법이라고 생각하고 분리시켜주었고 상태관리는 가장 상위 App컴포넌트에서 한번에 관리를 해주는것이 상태관리에 있어서 편리하다고 생각되어서 App컴포넌트를 상태관리 컴포넌트로 그리고 화면을 구성하는 컴포넌트들은 다시 Page컴포넌트로 묶어서 App컴포넌트와 분리시켜주었습니다. 하나의 컴포넌트가 하나의 역할을 맡고 있게 해서 더 깔끔해졌다고 생각합니다.   

 완성한 과제가 컴포넌트들이 복잡하게 많은 구조가 아닌 간단한 구조라 상위 컴포넌트를 만들어 하위 컴포넌트(들)를 그 상위컴포넌트들에 넣어준다는 것이 처음에는 파일의 수를 늘리고 코드를 더 작성하게 만든다는 생각에 왜 필요한 일인가에 대한 의문을 가지게 되었습니다. 그러다가 더 크게 생각해보니 컴포넌트들이 복잡하게 얽혀있고 스타일과 역할과 기능이 다 다른 군집일 때 그것을 잘 분리시켜주는 것 또한 컴포넌트의 역할 일 수 있고 하나의 컴포넌트의 하나의 역할이라는 기준과 부합하다는걸 깨닫고 상위 컴포넌트의 필요성에 대해 알게되었습니다. 

 가장 기본적인 원리들을 충실할 수 있는 코드들이라 기본을 잘 배우고 앞으로 나아가는 느낌이 듭니다. 앞으로 코드를 짤 때도 기본을 놓치지 않고 코딩하는 습관을 들여야겠습니다!

2020-10-05 13:00 UTC, merged