Render 'Hello React'
CodeSoom/week2-assignment-1 pull request #31
Opened 2020-09-21 10:09 UTC by gringrape

## 기능

  - Click me!를 클릭하면 숫자가 1씩 증가합니다.
  - 숫자 1 버튼을 누르면 숫자가 1씩 증가합니다.
  - 숫자 2 버튼을 누르면 숫자가 2씩 증가합니다.
  - 숫자 3 버튼을 누르면 숫자가 3씩 증가합니다.
  - 숫자 4 버튼을 누르면 숫자가 4씩 증가합니다.
  - 숫자 5 버튼을 누르면 숫자가 5씩 증가합니다.

## 제한 조건

  - if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
  - switch는 사용하실 수 없습니다.
  - let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
  - 함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
  - indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

## 요구사항

  - ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
  - 모든 인수 테스트를 통과시켜야 합니다.
  - 한 파일에는 하나의 컴포넌트만 있어야 합니다.

## Self 제한조건
- 작게 작업을 설계하고, 설계한 작업범위내에서 수행해야 합니다.
- 피드백이 가능한 작업만을 합니다.

2020-09-21 12:34 UTC, gringrape commented
## 작업 의도
강의에서 배운 관심사의 분리를 이용해, 
App 컴포넌트에는 상태를 관리하는 로직을 담았습니다.
상태를 정의하고, 상태를 변경시킬 수 있는 함수를 생성해서 하위 컴포넌트에 넘겼습니다.
하위컴포넌트는 받은 것을 이용하여 렌더링하는 로직만을 담았습니다.

## 주안점
- 억지로라도 인식범위를 좁혀서, 명확하게 지금 결과를 확인할 수 있는 작업만 하도록 노력했습니다
- 점진적인 구현이 되도록 하였습니다.

2020-09-21 16:28 UTC, Kihyun92 requested changes
많이 고민하고 구조를 분리해보신 것 같아요!👍

다만 관심사의 분리라는 의도를 조금 더 고민해보시면 파일들을 더 알맞게 쪼갤 수 있으실 것 같습니다!☺️

2020-09-21 16:28 UTC, Kihyun92 commented on src/App.jsx
> +}
좋습니다! 다만, App 컴포넌트에서 한가지 일만 하고 있지 않은 것 같습니다~ 강의 내용을 떠올려보시면 금방 해결하실 것 같습니다~👍

2020-09-21 16:28 UTC, Kihyun92 commented on src/App.jsx
> +  };
값을 받아와서 count에 해당 값만큼 더해주도록 한게 좋네요! 😁

다만, 매개변수의 이름이 'count 값을 증가 시켜주는 값'임을 알 수 있으면 더 좋을것 같아요~☺️

2020-09-21 23:53 UTC, gringrape commented on src/App.jsx
> +}
그렇군요. 상태를 관리하는 로직 외에도

1. Counter, Button 을 어떻게 화면에 배치하는지 (렌더링 하는지)
2. 각 컴포넌트를 클릭했을때, 무슨일을 할지

를 구체적으로 결정해주고 있네요.

2020-09-22 00:00 UTC, gringrape commented on src/App.jsx
> +}
@Kihyun92

일단 이렇게 책임을 다시 결정해봤습니다.

> App: 상태를 정의하고, 관리하는 도구를 만든다. 
> Page: 화면에 컴포넌트들을 배치하고 도구들을 나누어준다.
> 기타 Component: 주어진 도구를 이용해서 렌더링 한다.

2020-09-22 00:03 UTC, gringrape commented on src/App.jsx
> +  };
그러네요 함수를 사용하는쪽만 보면 무엇을 인자로 넣으라는건지 좀더 설명해줄 필요가 있네요. 
감사합니다 :)

2020-09-22 09:46 UTC, gringrape commented
## 작업내용
### Page Component 를 분리

2020-09-22 15:10 UTC, Kihyun92 requested changes
좋습니다! 고민을 많이 하면서 해주시니 제가 피드백 드릴게 거의 없네요 ㅎㅎ

2020-09-22 15:10 UTC, Kihyun92 commented on src/App.jsx
> +import Page from './Page';
```suggestion
import React, { useState } from 'react';

import Page from './Page';
```
공백 추가해주세요~ 모듈 간에도 역할이 있고, 지금은 import 하는게 별로 없어 괜찮을 수 있지만, 묶어서 관리하는 습관을 들이면 좋을 것 같습니다~

다른 파일들도 확인해보시고 적용해주세요~ 👍

2020-09-22 15:10 UTC, Kihyun92 commented on src/App.jsx
> +  const handleClick = ({ increment }) => {
```suggestion
  const handleClick = (increment) => {
```
이렇게 한다면 Page 컴포넌트에서도 조금 더 간결하게 사용 가능할 것 같아요~

2020-09-23 12:43 UTC, gringrape commented on src/App.jsx
> +import Page from './Page';
@Kihyun92 모듈 종류를 '컴포넌트'와 '라이브러리'로 구분하기 위함인가요?

2020-09-23 13:50 UTC, Kihyun92 commented on src/App.jsx
> +import Page from './Page';
정확합니다~ 지금은 라이브러리와 컴포넌트 밖에 없지만 프로젝트가 커질수록 사용되는 모듈의 종류도 매우 많아지게 되는데요. 이때 잘 묶어두면 훨씬 보기 쉽고 수정하기 쉽겠죠?

lint중에 `ordered-imports`를 사용해서 파일 형식에 따라 순서를 잡아주는게 있는데 이걸 쓰기도 합니다 :)

2020-09-23 14:07 UTC, gringrape commented on src/App.jsx
> +import Page from './Page';
그렇군요 그 rule 도 켜놓고 해야겠네요 ㅎㅎ
좋은것 알려주셔서 감사합니다!

2020-09-24 14:11 UTC, Kihyun92 approved these changes
좋습니다~ 이번 과제를 통해 어떤걸 배우셨나요? 한번 되돌아보면 좋을 것 같습니다~ :)

2020-10-05 12:56 UTC, merged