Week2 1 simple count app
CodeSoom/week2-assignment-1 pull request #33
Opened 2020-09-21 11:12 UTC by saseungmin

## 🚀 과제 목표
- [x] 각 컴포넌트 마다 각 파일로 분리하기 (하나의 파일에는 하나의 컴포넌트만)
- [x] `Click me!`를 클릭하면 숫자가 `1`씩 증가시키기
- [x] `1,2,3,4,5`를 클릭하면 `1,2,3,4,5`씩 증가시키기

## ✔ 제한 조건
- [x] `GuardClauses` 방법을 사용하기
- [x] `switch`는 사용❌
- [x] `let`은 ❌  `const`만을 사용⭕
- [x] 함수 이름과 변수 이름에 줄임말은 사용하실 수 없고 길더라도 명확하게!
- [x] `indent(인덴트, 들여쓰기) depth`를 `1`로 유지하기
### 🌈 요구사항
- [x] `ESLint`를 돌린 결과 아무런 문제가 없어야 합니다.
- [x] 모든 인수 테스트를 통과시켜야 합니다.
- [x] 한 파일에는 하나의 컴포넌트만 있어야 합니다.

2020-09-21 15:42 UTC, hannut91 requested changes

2020-09-21 15:42 UTC, hannut91 commented on src/index.jsx
> +
여기 두 줄이 띄워져 있는데 의도적으로 띄신건가요?

2020-09-21 15:42 UTC, hannut91 commented on src/index.jsx
> +import Page from './components/Page';
위에 빈 줄을 추가해서 리액트 라이브러리 임포트와 컴포넌트 임포트를 구분해주면 좋을 것 같아요

2020-09-21 15:42 UTC, hannut91 commented on src/index.jsx
> +
여기도 두 줄이 띄워져있네요

2020-09-21 15:42 UTC, hannut91 commented on src/components/Page.jsx
> +import Buttons from './Buttons';
여기 위에도 빈 줄 하나를 추가해서 리액트 라이브러리 임포트와 로컬 컴포넌트 임포트를 구분해주면 좋을 것 같아요

2020-09-21 15:42 UTC, hannut91 commented on src/components/Counter.jsx
> +    <button type="button" onClick={() => onClick()}>
버튼을 클릭했을 때 `onClick`함수를 실행하는 것 같아요. onClick에 함수의 레퍼런스를 바로 넘겨주는건 어떨까요?

2020-09-21 15:42 UTC, hannut91 commented on src/components/Buttons.jsx
> +import Button from './Button';
여기도 위에 빈 줄 하나를 추가해서 리액트 라이브러리와 로컬 컴포넌트 임포트를 구분해주면 좋을 것 같아요

2020-09-21 15:42 UTC, hannut91 commented on src/components/Button.jsx
> +    </button>
이 버튼을 클릭했을 때 `onClick`함수를 실행해서 숫자를 넘겨주는 것 같아요. 그래서 이 버튼을 숫자를 받고 숫자를 출력하며, 클릭하면 숫자가 반환이되는 역할만 할 수 있어요. 

만약에 이 버튼은 화면을 보여주는 역할만 하고 버튼을 클릭했을 때 어떤 일을할지 컴포넌트를 사용하는 입장에서 결정할 수 있도록 하려면 어떻게 해야할까요?

2020-09-22 13:30 UTC, hannut91 requested changes

2020-09-22 13:30 UTC, hannut91 commented on src/index.jsx
> +ReactDOM.render(<App />, document.getElementById('app'));
`index.js`파일 안에서 1. 렌더 2. `<App />`컴포넌트 정의 두 가지 일을 하고 있어요. 이 두 가지 일을 파일로 구분할 수 있을까요?

2020-09-22 13:30 UTC, hannut91 commented on src/components/Page.jsx
> +      <Counter count={count} onClick={() => onClick()} />
Counter앱으로 `onClick`함수의 레퍼런스를 그대로 넘겨주는 것 같아요. 그러면 바로 `onClick={onClick}`으로 사용할 수 있을 것 같아요

2020-09-22 13:30 UTC, hannut91 commented on src/components/Buttons.jsx
> +          {number}
<Button />
여기에 있는 내용이 `Button`컴포넌트의 children 이라는 속성으로 들어옵니다.
</Button>

그래서 `number`라는 속성을 쓸 필요없이 다음과 같이 쓸 수 있을거에요

```js
function Button({ children, onClick }) {
  return (
    <button type="button" onClick={onClick}>
      {children}
    </button>
  );
}
```

2020-09-22 14:55 UTC, saseungmin commented on src/components/Page.jsx
> +      <Counter count={count} onClick={() => onClick()} />
- 위에 같은 상황에서 아래와 같이 넘겨주면 `[object Object]`이런 형식으로 나옵니다.
```javascript
  return (
    <div>
      <p>Counter</p>
      <Counter count={count} onClick={onClick} />
```
- `App.jsx` 의 `handleClick`이 초기값을 잡아줘서 그런게 맞을까요?
```javascript
function handleClick(value = 1){
    setState({count: count + value});
}
```

2020-09-22 14:56 UTC, saseungmin commented on src/index.jsx
> +ReactDOM.render(<App />, document.getElementById('app'));
넵! `App.jsx`로 분리하였습니다.

2020-09-23 15:59 UTC, hannut91 approved these changes
강의 내용대로 잘 구현해주셨습니다. 관심사 분리가 굉장히 잘 되있습니다. 고생하셨습니다.

2020-09-23 15:59 UTC, hannut91 commented on src/components/Page.jsx
> +      <Counter count={count} onClick={() => onClick()} />
아 그렇군요 ㅎㅎ 제가 착각했네요. onClick으로 넘기는게 아무것도 없어서 헷갈렸습니다. 맞게 하신 것 같아요 ㅎㅎ

`onClick={() => onClick(1)}` 이렇게 했으면 어떤 값을 넘기고 있는지 알 수 있었을탠데 비어있어서 그냥 핸들러로 넘겨도 되지 않나 생각했습니다 ㅎㅎ

2020-09-23 15:59 UTC, merged