🎨 Implement counter structure
CodeSoom/week2-assignment-1 pull request #34
Opened 2020-09-21 12:58 UTC by Knoa0405

first pull request but, not complete counter
Just implement counter structure
구조만 잡고 PR 보냅니다~!
오늘 중으로 완성하고 추가 PR 보내겠습니다~

2020-09-21 14:13 UTC, Knoa0405 commented
첨에 조금 헤매다가 완성했습니다!

1. App 컴포넌트 안에는 state 관리와 핸들러 함수 같은 비즈니스 로직 처리 부분을 넣어주었습니다.

2. UI(view) 부분은 Buttons 와 ClickMeCounter 두 컴포넌트를 각각 파일을 따로 만들었습니다.

3. App 컴포넌트 반환값으로 view 컴포넌트들을 import 해와서 넣어주고 
   비즈니스 로직을 담당하는 App 컴포넌트에서 처리되는 값들을 view 부분을 담당하는 
   Buttons,ClickMeCounter 의 props로 전달하는 방법으로 해봤습니다.

2020-09-21 15:47 UTC, hannut91 requested changes

2020-09-21 15:47 UTC, hannut91 commented on src/ClickMeCounter.jsx
> +
여기 빈 줄이 두 줄이 들어가있는데 의도하신건가요?

2020-09-21 15:47 UTC, hannut91 commented on src/ClickMeCounter.jsx
> +
여기 빈줄이 들어간 것 같아요

2020-09-21 15:47 UTC, hannut91 commented on src/ClickMeCounter.jsx
> +
여기도 빈 줄이 두 줄이 들어가 있네요

2020-09-21 15:47 UTC, hannut91 commented on src/index.jsx
> +
여기도 빈 줄이 두 줄이 들어가 있네요

2020-09-21 15:47 UTC, hannut91 commented on src/index.jsx
> +import ClickMeCounter from './ClickMeCounter';
위에 빈 줄 하나를 추가해서 리액트 라이브러리 임포트와 로컬 컴포넌트 임포트를 구분해주면 좋을 것 같아요

2020-09-21 15:47 UTC, hannut91 commented on src/Buttons.jsx
> +
여기도 빈 줄이 두 줄이 들어가있네요

2020-09-21 15:47 UTC, hannut91 commented on src/Buttons.jsx
> +export default Buttons;
`export default function`으로 바로 써줄 수 있습니다. 하지만 팀의 컨벤션마다 다를 수 있으니 참고로만 알아두시면 좋을 것 같습니다

2020-09-21 15:47 UTC, hannut91 commented on src/Buttons.jsx
> +        <button type="button" key={number} onClick={() => onClick(number)}>{number}</button>
이 버튼도 별도의 컴포넌트로 분리할 수 있을까요? 별도로 분리하되 버튼은 화면에 보여주는 역할만 하고, 컴포넌트를 사용하는 입장에서 클릭했을 때 어떤 동작을 할지 결정할 수 있도록 해보면 좋을 것 같아요

2020-09-22 06:14 UTC, Knoa0405 commented on src/Buttons.jsx
> +        <button type="button" key={number} onClick={() => onClick(number)}>{number}</button>
buttons 안에 있는 button도 컴포넌트로 분리할 수 있겠네요! 조금 복잡해지는게 아닐까 생각되지만,
확장성을 고려하고 유지,보수를 생각한다면 버튼만 따로 빼서  컴포넌트를 만들어두면 스타일을 새로 입히거나 업데이트 할 때도 유용하겠네요~! 수정해보고 PR 보내겠습니다!!

2020-09-22 06:18 UTC, Knoa0405 commented on src/Buttons.jsx
> +export default Buttons;
넵 export 할 때도 전체를 넘기느냐 아니면 변수 하나만 넘기는가에 따라서도 또 다르게 쓰더라구요
export { variable value } 이런 것도 있던데 정확히 잘 모르겠습니다! import 해올때도 { } 쓰는게 있고 안쓰는 게 있고요
혹시 이것 관련해서 공부할 때 참고할만한 자료가 있을까요? 모를때마다 찾아보긴했는데 정리가 안되네요.

2020-09-22 06:19 UTC, Knoa0405 commented on src/index.jsx
> +import ClickMeCounter from './ClickMeCounter';
넵 서로 맥락상 다른 부분이라고 보고 띄워주는군요 임포트 부분까진 생각못했네요ㅎ 수정하겠습니다~!

2020-09-22 06:25 UTC, Knoa0405 commented on src/ClickMeCounter.jsx
> +
한줄씩 띄워준다는게 2줄이 들어갔네요.. 수정하겠습니다~!
그리고 파일을 저장할 때마다 eslint 로 자동 포맷을 해주도록 설정해주고 쓰고 있는데 혹시 현업에서는 eslint 로 포맷 + 규칙을 지키면서 하나요? 예전부터 공부할 때 prettier-eslint plugin 설치해주고 prettier 포맷에 eslint 규칙을 적용해서 썼는데 이건 회사마다 다르겠죠?

2020-09-22 06:38 UTC, hannut91 commented on src/ClickMeCounter.jsx
> +
맞습니다 ㅎㅎ 회사 컨벤션에 따르면 좋을 것 같아요

2020-09-22 06:38 UTC, hannut91 commented on src/Buttons.jsx
> +export default Buttons;
https://ko.javascript.info/modules-intro

이 문서를 참고하시면 좋습니다 ㅎㅎ

2020-09-22 13:41 UTC, Knoa0405 commented on src/Buttons.jsx
> +export default Buttons;
넵! 감사합니다~

2020-09-22 13:56 UTC, Knoa0405 commented
## **< 첫번째 리팩토링 >**

1. 코드 맥락의 흐름에 맞게 한줄씩 띄워줬습니다. - 두줄 띄워진 곳 수정했습니다.
( 임포트 부분도 라이브러리 임포트와 로컬 임포트 사이에 한줄을 띄워줬습니다. )

2. Buttons 컴포넌트 안에 button 들을 Button 컴포넌트로 따로 분리해줬는데 key 값이 props로는
전달이 안되서 Buttons 안에서 map으로 Button 컴포넌트를 만들어주고 Button 컴포넌트 안에 
children 값으로 Button 컴포넌트 안에 button에 key를 전달하는 방식을 사용하니 해결되었습니다. 
왜 그런지 모르고 적용했는데 관련되어 도움될 만한 자료가 있을까요?
key는 props로 안쳐주는 건가요? 그냥 가상의 프로퍼티라? 그런건가요? 모르겠습니다..ㅎ

2020-09-23 16:04 UTC, hannut91 requested changes

2020-09-23 16:04 UTC, hannut91 commented on src/Button.jsx
> +      onClick={() => onClick(children)}
`children`으로 현재 숫자만 입력했으니 문제가 없는 것 처럼 보입니다. 하지만 children에 여러 값이 들어간다면 어떻게 될까요? 예상한대로 동작하기 어려울 것 같아요. 당장에 ClickMeCounter를 이 버튼 컴포넌트로 구현하려고만 해도 제대로 동작하지 않겠죠

`key`는 `map`을 사용해서 여러개가 있을 때 사용하는 것이기 때문에 여기서는 사용하지 않아야 합니다.

이 컴포넌트는 버튼을 클릭했을 때 주어진 UI 클릭 이벤트만 다루는 일만 해야합니다. 지금은 onClick으로 값을 넘기는 일도 같이하고 있어요. 사용하는 입장에서 이 버튼일 클릭됐을 때 어떻게 동작할지 결정할 수 있도록 하려면 어떻게 해야 할까요?

2020-09-23 16:04 UTC, hannut91 commented on src/Buttons.jsx
> +
여기 빈 줄이 들어갔네요

2020-09-23 16:04 UTC, hannut91 commented on src/index.jsx
> +  }
굉장히 비슷한 일을 하는 것 같은데 중복을 제거할 수 있을까요?

2020-09-23 16:04 UTC, hannut91 commented on src/index.jsx
> +ReactDOM.render(<App />, document.getElementById('app'));
`index.jsx`파일에서 App컴포넌트를 정의하는 일과 render하는 일 두 가지 일을 하고 있는 것 같아요. 파일로 이 두 가지일을 분리시킬 수 있을까요?

2020-09-23 16:06 UTC, hannut91 commented
리액트의 리스트와 키에 대한 내용은 다음 문서를 읽어보시면 좋을 것 같습니다.

See also
  - https://reactjs.org/docs/lists-and-keys.html

2020-09-26 02:19 UTC, Knoa0405 commented on src/Button.jsx
> +      onClick={() => onClick(children)}
onClick으로 값을 넘기지 않고 onClick 이 발생할 때마다 그 해당 값에 맞는
숫자를 + 해줄 수 있는 방법이 떠오르지 않습니다.

조금 더 방향성을 제시해주실 수 있으신가요?

2020-09-26 02:24 UTC, Knoa0405 commented
# 두번째 리팩토링 ( 과제 2를 먼저 하다보니 늦었네요ㅠ)

1. key Lists 에 대해서 주신 자료를 보고 key 라는 특별한 녀석을 props로
전달해줄려고 한 것이 잘못된 방향의 주된 원인이었습니다.

말씀해주신대로 children 에 전달해준 것과 key 를 전달해준 것 모두 잘못된 
것을 알게 된 후 좀 더 생각해서 해야 겠다고 많이 느꼈습니다.
"아 동작된다 끝" 으로 생각하고 PR 보내는 것 같습니다.
이부분은 스스로 반성하고 고쳐야겠습니다.

-------

> 이 컴포넌트는 버튼을 클릭했을 때 주어진 UI 클릭 이벤트만 다루는 일만 해야합니다. 지금은 onClick으로 값을 넘기는 일도 같이하고 있어요. 사용하는 입장에서 이 버튼일 클릭됐을 때 어떻게 동작할지 결정할 수 있도록 하려면 어떻게 해야 할까요?

2. 위에서 말씀해주신 부분에 대해서는 방법이 떠오르지 않아 수정을 못했습니다. 조금 더 방향을 제시해주시면 고민을 어떤 식으로 해나가야 할지 도움이
될 것 같습니다!
----
3. 중복 제거해주고, index.jsx 에 있는 App 컴포넌트를 따로 파일로 분리해서
나눴습니다.

2020-09-26 15:51 UTC, hannut91 requested changes

2020-09-26 15:51 UTC, hannut91 commented on src/Button.jsx
> +}
```js
export default function Button({ children, onClick, }) {
  return (
    <button
      type="button"
      onClick={onClick}
    >
      {children}
    </button>
  );
}
```

`Button`컴포넌트를 위와 같이 작성하면 이 컴포넌트는 컴포넌트 태그 안에 내용들을 보여주고, 버튼을 클릭했을 때 주어진 핸들러를 실행하는 역할만 합니다. 실제 클릭했을 때 어떻게 동작할지는 이 컴포넌트에서는 전혀 모릅니다. 만약에 클릭했을 때 `alert`창이 뜨도록 하려면

```js
<Button onClick={() => alert('Hello!')} />
  버튼을 클릭하면 Hello가 보입니다.
</Button
```

처럼 사용할 수 있죠. 따라서 사용하는 입장에서 클릭했을 때 어떤 동작이 이루어질지 결정합니다. 그런데 만약 `Button`컴포넌트에서 클릭했을 때 어떻게 동작할지 결정이 되어있다면 이 컴포넌트는 사용될 수 없겠죠.

`ClickMeCounter`컴포넌트에서 

```js
      <button type="button" onClick={() => onClick(1)}>
        Click me (
        {count}
        )
      </button>
```
부분이 있는데 이 부분도 `Button` 컴포넌트를 이용해서 표현해줄 수 있겠죠?

2020-09-27 13:40 UTC, Knoa0405 commented on src/Button.jsx
> +}
button에서 onClick에 value 값을 전달하지 않고 count에 value 를 어떻게 하면 더할 수 있을지 해결하지 못했습니다.

2020-09-27 13:42 UTC, hannut91 commented on src/Button.jsx
> +}
`Button`을 사용할 때 `onClick`에 전달하면 됩니다.

```js
<Button onClick={() => onClick(1)} />
```

2020-09-27 13:42 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ

2020-09-27 13:46 UTC, merged

2020-09-27 14:00 UTC, Knoa0405 commented on src/Button.jsx
> +}
아!! 그렇네요ㅎㅎ; 미처 생각을 못했네요.