[과제1] 카운터 앱 만들기
CodeSoom/week2-assignment-1 pull request #35
Opened 2020-09-21 14:02 UTC by juunini

# 기능
- [x] Click me!를 클릭하면 숫자가 1씩 증가합니다.
- [x] 숫자 1 버튼을 누르면 숫자가 1씩 증가합니다.
- [x] 숫자 2 버튼을 누르면 숫자가 2씩 증가합니다.
- [x] 숫자 3 버튼을 누르면 숫자가 3씩 증가합니다.
- [x] 숫자 4 버튼을 누르면 숫자가 4씩 증가합니다.
- [x] 숫자 5 버튼을 누르면 숫자가 5씩 증가합니다.

# 요구사항
- [x] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [x] 모든 인수 테스트를 통과시켜야 합니다.
- [x] 한 파일에는 하나의 컴포넌트만 있어야 합니다.

2020-09-21 15:52 UTC, hannut91 requested changes

2020-09-21 15:52 UTC, hannut91 commented on src/index.jsx
> +import App from './App';
위에 빈줄 하나를 추가해서 라이브러리 임포트와 로컬 컴포넌트 임포트를 구분해주면 좋을 것 같아요

2020-09-21 15:52 UTC, hannut91 commented on src/components/ClickMeButton.jsx
> +/* eslint-disable react/jsx-one-expression-per-line */
이건 어떤 이유 때문에 추가하셨는지 설명해주실 수 있나요?

2020-09-21 15:52 UTC, hannut91 commented on src/components/NumberButton.jsx
> +export default NumberButton;
`export default function`으로 한 줄에 써줄 수 있습니다. 어떻게 할지는 팀의 컨벤션에 따라 다르므로 참고로만 알아두시면 좋을 것 같습니다

2020-09-21 15:52 UTC, hannut91 commented on src/components/NumberButton.jsx
> +}
숫자를 입력받는 버튼이라서 NumberButton으로 사용하신 것 같아요. 단순히 입력받은 값을 보여주고 클릭했을 때 핸들러 함수를 실행한다면 Number라는 이름이 아니더라도 사용할 수 있을 것 같아요.

2020-09-21 15:52 UTC, hannut91 commented on src/App.jsx
> +import NumberButton from './components/NumberButton';
여기도 위에 빈 줄 하나를 추가해서 라이브러리 임포트와 컴포넌트 임포트를 구분해주면 좋을 것 같아요

2020-09-21 23:29 UTC, juunini commented on src/components/ClickMeButton.jsx
> +/* eslint-disable react/jsx-one-expression-per-line */
`({value)}` 로 쓰고싶은데 저걸 쓰지 않으면
```javascript
(
{value}
)
```
가 되서 썼습니다.

2020-09-21 23:35 UTC, juunini commented on src/index.jsx
> +import App from './App';
예전부터 라이브러리와 로컬파일 import룰 한줄 띄울까 붙여쓸까 고민하다가 ESLint도 이런걸 강제하지 않고 다른 언어에서도 이런걸 종종 붙여쓰는게 많다보니 그냥 붙여서 썼습니다.

이 부분도 역시나 정답은 없고 의도가 잘 표현되는 것이 가장 좋은 부분이군요. 트레이너님 덕분에 자신감을 얻고 한줄 띄워서 써보겠습니다. 감사합니다.

2020-09-21 23:38 UTC, juunini commented on src/components/NumberButton.jsx
> +}
나름 직관적으로 쓴다고 "숫자버튼" 이라고 썼는데 기능에 대해서는 생각을 안한 작명이었던듯 합니다 ^^;

조금 더 고민해보겠습니다.

2020-09-22 13:33 UTC, hannut91 commented on src/index.jsx
> +import App from './App';
맞습니다 ㅎㅎ 사실 가장 중요한 것은 팀의 컨벤션에 따르는게 맞겠죠. 
Golang은 내부 라이브러리, 외부 라이브러리, 로컬 파일을 한 줄로 구분합니다.

2020-09-22 14:17 UTC, hannut91 requested changes

2020-09-22 14:17 UTC, hannut91 commented on src/components/IncreaseCountButton.jsx
> +function IncreaseCountButton({ value, onClick }) {
이 컴포넌트의 이름이 왜 IncreateCountButton인지 모르겠어요.

2020-09-22 14:23 UTC, juunini commented on src/components/IncreaseCountButton.jsx
> +function IncreaseCountButton({ value, onClick }) {
아.... onClick에 들어가는 함수는 이 컴포넌트의 기능이 아니었구나 하고
아차싶은 느낌을 받았습니다;;

2020-09-23 04:24 UTC, juunini commented
# 작업 내용
- `IncreaseCountButton`컴포넌트의 이름을 `Button` 으로 변경했습니다.
- `Button`을 여러개 만들어주는 `ActionByValueButtons` 라는 컴포넌트를 만들었습니다.
- 숫자를 입력받아 해당 숫자만큼 count가 오르는 기능을 추가했습니다.
  - `NumberInput` 컴포넌트를 생성했습니다.
  - 이 부분에 해당하는 테스트를 추가했습니다.

# 고민사항
- `Button` 을 여러개 만드는 컴포넌트를 만드는게 옳지 않았던 것 같은 기분이 듭니다...
  - 그 컴포넌트의 이름이 `ActionByValueButtons` 라는 것도 그렇고, 표현이 굉장히 애매해졌습니다.
  - 그냥 빼서 다시 펼쳐놓을까 고민중이기도 합니다.

2020-09-23 16:33 UTC, hannut91 requested changes

2020-09-23 16:33 UTC, hannut91 commented on src/components/Button.jsx
> +}
특정한 값을 출력하도록 `value`라는 이름으로 props로 사용하신 것 같아요. `children`을 사용하시면 같은 목표를 달성하면서 더 명확하게 의도를 드러낼 수 있을거에요

See also
  - https://reactjs.org/docs/composition-vs-inheritance.html

2020-09-23 16:33 UTC, hannut91 commented on src/App.jsx
> +        />
어떤 배열이든 버튼 목록을 만들어서 클릭했을 때 그 값을 호출하도록 만드신 것 같아요. 그런데 이런 추상화가 오히려 이해하기 어렵게 만든 것 같아요. 

value는 아무런 의미도 없는 단어고, List는 자료형을 나타내는 이름 같은데 실제로 받는 자료형은 배열이에요. 

아래랑 비교해서 어떤게 더 이해하기 쉬운지 비교해보시면 좋을 것 같아요

```js
{[1, 2, 3, 4, 5].map((it) => (
  <Button key={it} onClick={() => handleClick(it)}>
    {it}
  </Button>
))}
```

혹은 이런 것 어떤가요?

```js
function SequenceButtons({ length, onClick }) {
  return (
    <>
      {Array.from({ length }, (_, i) => i + 1).map((it) => (
        <Button key={it} onClick={() => onClick(it)}>
          {it}
        </Button>
      ))}
    </>
  )
}
```

2020-09-24 11:05 UTC, juunini commented on src/components/Button.jsx
> +}
아!
children을 쓰면 따로 값을 전달하지 않아도 HTML 태그처럼 안에 내용을 써서 전달할 수 있군요!
감사합니다!

2020-09-24 11:07 UTC, juunini commented on src/App.jsx
> +        />
역시 만들면서도 의미를 느끼지 못했는데 그런거였군요.
무의미한 행동이었지만 다음부턴 이런 무의미한 행동을 하기 전에 한번 더 생각해볼 수 있을 것 같습니다. 감사합니다.

2020-09-24 11:12 UTC, juunini commented
# 오늘 작업 내용
- `Button` 컴포넌트에 내부에 사용될 내용을 children을 통해 받도록 변경하였습니다.
- `ActionByValueButtons` 컴포넌트를 삭제했습니다.

# 알게된 것
- children을 쓰면 HTML태그 처럼 안에 내용을 쓸 수 있는걸 알게되었습니다.
- 왜 하는지 모르겠으면 무작정 하려 들지 말고 일단 놔두자. 확실한 이유가 있을 때 변경하자.

2020-09-24 14:37 UTC, hannut91 requested changes
저는 여러가지 시도를 하시는게 좋아요. 다양한 시도를 하면서 많이 배울 수 있다고 생각합니다 ㅎㅎ 때로는 `왜`라는 것은 하기 전까지 이해하기 어려운 경우가 많으니까요

2020-09-24 14:37 UTC, hannut91 commented on src/App.jsx
> +        />
이 `ClickMeButton` 대신에 `Button`컴포넌트를 이용할 수 있을꺼요?

2020-09-25 10:47 UTC, juunini commented on src/App.jsx
> +        />
꼭 `ClickMeButton` 컴포넌트를 만들 필요가 없었군요!
애초에 children을 쓰기 전 부터도 그랬었는데 왜 생각을 못했었는지 ㅎㅎ;

2020-09-25 10:58 UTC, juunini commented
# 오늘 작업 내용
- `ClickMeButton` 컴포넌트 제거

# 생각중인 것
- 사실 increase 의 인풋 필드와 버튼을 만든 것은 
  ```javascript
  <ActionByValueButtons
    valueList={[1, 2, 3, 4, 5]}
    onClick={handleClick}
  />
   ```
  이 부분이 잘 한건가 아닌건가 생각해보며 제 생각을 제 나름 검증하기 위해 만들었던 부분입니다.
  - 결국 인풋과 버튼을 하나로 묶는 컴포넌트를 만들지 않았고, 만들 필요도 없었으며 결국은 필요없었구나 라는 생각이 들었고, 트레이너님께서도 없애는게 낫겠다는 말씀을 해주셔서 삭제했었습니다.
  - 꼭 삽질하는게 의미가 없진 않구나 라고 생각중입니다. 더 많이 생각하고 어제보다 나아졌다면 결국 더 좋은게 아닐까 하고요...
- 왠지 일주일간 고생했지만 아샬님의 풀이를 보면 또 허탈할 것 같은 기분이 듭니다 ㅎㅎ
  - 언젠가 저도 더 실력이 좋아지면 아샬님처럼 말 하는대로 코드가 나오고, 보는 사람도 쉽게 알아볼 수 있는 그런 코드를 짜는 좋은 개발자가 되고싶다는 생각이 듭니다.

2020-09-25 14:50 UTC, hannut91 approved these changes
저도 술술 코드가 나왔으면 좋겠네요. 많은 시행착오로 겪은 만큼 배운점도 많으리라 생각합니다 ㅎㅎ

2020-09-25 14:56 UTC, hannut91 commented
처음 코드와 마지막 코드를 비교해보시면 좋을 것 같습니다 ㅎㅎ

2020-09-25 14:56 UTC, merged