week2-1 make counter app
CodeSoom/week2-assignment-1 pull request #36
Opened 2020-09-21 15:23 UTC by JamieShin0201

안녕하세요^^

1. NumberButton 컴포넌트를 생성했습니다.
2. Counter 컴포넌트를 생성했습니다.
3. NumberrButton을 가진 NumberButtons 컴포넌트를 생성했습니다.
4. Counter와 NumberButtons를 가진 Page 컴포넌트를 생성했습니다.
5. App 컴포넌트를 만들어 그 안에 상태관리 및 함수 비즈니스로직을 처리하였습니다..

2020-09-22 14:23 UTC, Kihyun92 requested changes
전반적으로 이번 강의를 열심히 들으시고, 의도에 대해 느껴보신것 같아요~

조금 더 완벽한 코드가 되려면 어떻게 해야할까 하는 생각에서 피드백을 남겨봤습니다 👍

2020-09-22 14:23 UTC, Kihyun92 commented on src/App.jsx
> +import Page from './Page';
```suggestion
import React, { useState } from 'react';

import Page from './Page';
```
한 줄 띄워주세요~ 모듈 간에 역할이 다르기 때문에 분리해두면 좀더 보기 편할 것 같아요 :)

2020-09-22 14:23 UTC, Kihyun92 commented on src/App.jsx
> +  }
두 함수가 비슷한 일을 하는것 같아요~

2020-09-22 14:23 UTC, Kihyun92 commented on src/App.jsx
> +      handleClickNumber={handleClickNumber}
`onClick={handleClick}`과 같이 컨벤션을 맞춰주는건 어떨까요??

참고: https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2020-09-22 14:23 UTC, Kihyun92 commented on src/NumberButton.jsx
> +function NumberButton({ children, onClick }) {
재사용성 측면에서 이 컴포넌트의 네이밍은 어떤가요?
제가 보기엔 이 컴포넌트는 단순히 버튼인 것 같아서요 :)

2020-09-22 14:23 UTC, Kihyun92 commented on src/index.jsx
> +import App from './App';
여기도 공백을 추가해주는게 좋을 것 같아요~

2020-09-23 02:05 UTC, JamieShin0201 commented
안녕하세요ㅎㅎ

1. handleClick 함수와 handleClickNumber 함수의 역할이 비슷하여 하나의 함수로 바꾸었습니다.
2. Naming Convention에 맞게 수정하였습니다.
3. 컴포넌트 이름을 변경하였습니다. 
(
NumberButtons -> Buttons
NumberButton -> Button
Page -> CounterPage
)

1. CounterPage
  1-1. Counter
    1-1-1. Button
  1-2. Buttons
    1-2-1. Button

다음과 같은 구조로 변경하였습니다.

감사합니다^_^

2020-09-23 14:00 UTC, Kihyun92 requested changes
좋습니다~ 과제의 의도에 대해서 이해를 하신것 같네요 :)
이번 과제 마지막 피드백일 것 같습니다 👍

2020-09-24 00:38 UTC, JamieShin0201 commented on src/CounterPage.jsx
> +        count={count}
아니요.... 필요없네요..
수정하였습니다 ㅎ.ㅎ

2020-09-24 00:39 UTC, JamieShin0201 commented
안녕하세요~

1. Buttons 컴포넌트에서 사용하지 않는 count 변수를 삭제하였습니다.
2. Buttons 에서 Button으로 onClick 매개변수를 넣는 시점을 바꾸었습니다.

감사합니다^^

2020-09-24 14:19 UTC, Kihyun92 requested changes

2020-09-24 14:19 UTC, Kihyun92 commented on src/Button.jsx
> +    <button type="button" onClick={() => onClick(children)}>
기존 방식과 같이 Buttons에서 매개변수를 넣어준다면 Buttons만 확인하고 수정하면 됐지만, 이렇게 되면 Button에서도 children에 무슨 값이 넘어오는지 알아야할 것 같네요.
지금 같은 구조에선 간단해서 큰 문제가 되지 않을 수 있지만, 추후 확장성을 생각해본다면 기존 방식이 더 낫지 않나 싶은데, 어떤가요?

2020-09-25 08:35 UTC, JamieShin0201 commented on src/Button.jsx
> +    <button type="button" onClick={() => onClick(children)}>
네.. 맞습니다! 무조건 최하위에서 매개변수를 넣어주면 좋을거 같다고 착각했습니다!. 
Button 컴포넌트의 확장성을 위해 Button컴포넌트를 만들때 매개변수를 넣어주면 더 좋을거 같습니다.

수정하였습니다.^^

2020-09-25 12:12 UTC, Kihyun92 approved these changes
좋습니다~ 처음 코드와 지금 코드가 어떻게 변했나요? 한번 생각해보시면 좋을 것 같아요 👍

2020-09-26 06:47 UTC, JamieShin0201 commented
처음 코드와 비교했을때 

1. Button 이라는 작은 컴포넌트를 만들어 Buttons 컴포넌트와 Counter 컴포넌트에 재사용하게 되었습니다.
2. 비슷한 역할을 하는 함수가 하나로 합쳐졌습니다.
3. 전반적으로 네이밍이 좋아졌습니다.

아직 많이 어렵지만 컴포넌트를 어떻게 쪼개고 재사용 가능하게 만들지 조금 알게 된거 같습니다.! ㅎ.ㅎ

2020-10-05 12:59 UTC, merged