Create counter app
CodeSoom/week2-assignment-1 pull request #37
Opened 2020-09-21 15:25 UTC by smilee

Create counter app to implement requirements.

2020-09-22 13:44 UTC, hannut91 requested changes

2020-09-22 13:44 UTC, hannut91 commented on src/CounterController.jsx
> +const CounterController = ({ difference, onClick }) => (
`Controller`라는 이름이 어떤 의미를 가지고 있나요? 컴포넌트명만 보고 판단하기에는 어려운 것 같아요.

2020-09-22 13:44 UTC, hannut91 commented on src/CounterController.jsx
> +  </button>
버튼을 클릭했을 때 onClick 함수로 { difference }라는 파라미터로 실행하는 것 같아요. 만약에 이 파라미터를 실행하는 것을 여기서 결정하지 않고 <CounterController />라는 컴포넌트를 사용할 때 결정할 수 있도록 하려면 어떻게 해야할까요? 그리고 그렇게 한다면 어떤 차이가 있을까요?

2020-09-22 13:44 UTC, hannut91 commented on src/Counter.jsx
> +
파일명이랑 컴포넌트명이 다른 것 같아요. 의도적으로 다르게 사용하신건가요?

2020-09-22 13:44 UTC, hannut91 commented on src/Page.jsx
> +
여기 빈 줄이 들어간 것 같아요

2020-09-22 13:44 UTC, hannut91 commented on src/Counter.jsx
> +);
만약에 1씩 증가하는 것이 아닌 2씩 증가하는 다른 카운터 버튼을 만든다면 어떻게 해결해야 할까요? 이 컴포넌트를 재사용할 수 있을까요? 혹은 그렇게 하려면 어떻게 해야 할까요?

2020-09-22 14:39 UTC, smilee commented on src/Counter.jsx
> +
아뇨, 이름을 고르다가 깜박하고 안 바꾼 것 같습니다. 😅

2020-09-22 14:47 UTC, smilee commented on src/Counter.jsx
> +);
얘도 `difference`를 받게 변경하겠습니다~

2020-09-22 14:53 UTC, smilee commented on src/CounterController.jsx
> +const CounterController = ({ difference, onClick }) => (
`Count`를 조작한다는 의미로 쓴 것이긴 한데 개발용어로는 핀트(?)가 조금 다를 수 있을 것 같습니다. 좋은 이름 추천받습니다!

2020-09-22 14:55 UTC, smilee commented on src/CounterController.jsx
> +  </button>
말씀하시는 컴포넌트가 어떤 컴포넌트인지 이름이 빠졌어요. 😢

2020-09-23 06:50 UTC, smilee commented on src/CounterController.jsx
> +  </button>
"라는"을 빼고 읽는다면 이 컴포넌트 말고 `Counter` 컴포넌트의 경우, 말씀하신대로 하면  prop을 하나 덜 내려도 됩니다. 그리고 이 컴포넌트에도 같이 적용한다면 prop 수는 같겠지만 상위 컴포넌트에서 각 컴포넌트에 어떤 `difference`값이 들어가는지 알 수 있습니다.

2020-09-23 16:37 UTC, hannut91 requested changes

2020-09-23 16:37 UTC, hannut91 commented on src/CountController.jsx
> +);
왜 이름이 `CountController`인지 모르겠어요. 이 컴포넌트는 특정한 값을 받아서 값을 출력하고, 버튼을 클릭했을 때 핸들러 함수를 호출하는 일만하고 있어요.

2020-09-23 16:37 UTC, hannut91 commented on src/Counter.jsx
> +);
하는일만 비교해보면 사실 CounterController랑 거의 같은 일을 하고 있어요. 주어진 것을 출력하고, 클릭한 UI이벤트를 처리하는 일을 하고 있어요. 비슷한 것을 하나의 개념으로 모을 수 있을까요?

See also
  - https://reactjs.org/docs/composition-vs-inheritance.html

2020-09-24 08:49 UTC, smilee commented on src/CountController.jsx
> +);
기능을 놓고보면 그렇네요.

2020-09-24 08:49 UTC, smilee commented on src/Counter.jsx
> +);
반영했습니다.

2020-09-24 14:39 UTC, hannut91 requested changes
이름이 훨씬 좋아졌네요! 하나만 수정하면 될 것 같아요

2020-09-24 14:39 UTC, hannut91 commented on src/Page.jsx
> +          difference={number}
이 속성은 더 이상 사용되지 않으니 삭제해도 좋을 것 같아요

2020-09-25 15:32 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 처음 작성한 코드와 나중에 작성한 코드를 비교해보시면 좋을 것 같습니다!

2020-09-25 15:33 UTC, merged

2020-09-26 02:03 UTC, smilee commented
> 고생하셨습니다 ㅎㅎ 처음 작성한 코드와 나중에 작성한 코드를 비교해보시면 좋을 것 같습니다!

혹시 그것을 쉽게 하는 방법이 있나 찾는 중입니다. ㅎㅎ