Dongjo/week2 assignment 1
CodeSoom/week2-assignment-1 pull request #40
Opened 2020-09-21 16:52 UTC by ParkDongJo

--------------------------------------------------------------------------------------------------------------
### [ 작업내용 ]
- [ ] 강의보고 코드 옮기기
- [ ] 파일 분리시키기
- [ ] 버튼 기능 구현하기
- [ ] 코드 개선하기
- [ ] lint & test 최종 통과 

### [ 시간 남을 시 할 일 ]
- 
--------------------------------------------------------------------------------------------------------------

2020-09-22 13:34 UTC, hannut91 commented
시작이 반입니다 ㅎㅎ

2020-09-23 17:19 UTC, ParkDongJo commented
> 시작이 반입니다 ㅎㅎ
@hannut91 
ㅠ 이번주 좀 피할수 없는 회식이 연달아 있었습니다. 그래도 회식 이후에 새벽 2시 반까지 과제를 수행하여.. 겨우 1과제를 마쳤습니다.
따끔한 피드벡 부탁드립니다.

2020-09-24 14:45 UTC, hannut91 requested changes
과제의 의도는 상태를 변경하는 것과 화면에 보여주는 것과 사용자 이벤트를 다루는 컴포넌트를 분리하여 관심사의 분리를 하는 것입니다. Context API를 이용해서 중복을 제거해주셨지만, `Counter` 컴포넌트가 상태에 의존하고, UI를 다루는  두 가지 일을 하고 있어요.

2020-09-24 14:45 UTC, hannut91 commented on src/components/Button.jsx
> +export { Button, Buttons };
하나의 파일에는 하나의 컴포넌트만 정의되도록 해주세요

2020-09-24 14:45 UTC, hannut91 commented on src/App.jsx
> +import AppContext from './context/AppContext';
리액트 라이브러리 임포트와 로컬 컴포넌트 사이에 빈 줄 하나를 추가해서 구분해주면 좋을 것 같아요.

2020-09-24 14:45 UTC, hannut91 commented on src/App.jsx
> +        },
`handleClick`을 별도의 핸들러 함수로 추출하면 좋을 것 같아요

2020-09-24 14:45 UTC, hannut91 commented on src/index.jsx
> +import App from './App';
여기도 위에 빈 줄 하나를 추가해주는게 좋을 것 같아요

2020-09-24 14:45 UTC, hannut91 commented on src/components/Counter.jsx
> +import AppContext from '../context/AppContext';
여기도 위에 빈 줄 하나를 추가해서 구분해주면 좋을 것 같아요

2020-09-24 14:45 UTC, hannut91 commented on src/components/Counter.jsx
> +    </button>
이 부분을 `Button`컴포넌트를 이용할 수 있을까요?

2020-09-25 17:08 UTC, hannut91 requested changes

2020-09-25 17:08 UTC, hannut91 commented on src/App.jsx
> +      <Counter count={count} onClick={handleClick} />
`<Counter />`를 사용하신 부분을 `Button`컴포넌트만을 사용해서 똑같이 기능을 구현할 수 있을까요? 가능하다면 가능한 이유는 무엇일까요?

2020-09-25 17:08 UTC, hannut91 commented on src/components/Counter.jsx
> +
여기 빈 줄이 두 줄이 들어갔습니다

2020-09-25 17:24 UTC, ParkDongJo commented on src/App.jsx
> +      <Counter count={count} onClick={handleClick} />
@hannut91 
아!!!....
`
       <Button onClick={handleClick}>
        Click Me!
        {count}
      </Button>
`
이러면 되는군요.. 아니 왜.. 이걸 생각못했지 ㅠ 가르침 감사합니다.

2020-09-25 17:25 UTC, ParkDongJo commented on src/App.jsx
> +      <Counter count={count} onClick={handleClick} />
앞으로 컴포넌트의 재사용을 적극 활용해야겠네요. 그리고 그렇게 구조를 짜려고 더 노력해야겠다는 생각이 듭니다.

2020-09-27 13:44 UTC, hannut91 approved these changes
고생하셨습니다 ㅎㅎ 바쁘신데 불구하고 과제를 잘 진행해주셨네요

2020-09-27 13:45 UTC, merged