Count/Divide 과제
CodeSoom/week2-assignment-1 pull request #41
Opened 2020-09-22 01:50 UTC by comejtome508

**기능**
Click me!를 클릭하면 숫자가 1씩 증가합니다.
숫자 1 버튼을 누르면 숫자가 1씩 증가합니다.
숫자 2 버튼을 누르면 숫자가 2씩 증가합니다.
숫자 3 버튼을 누르면 숫자가 3씩 증가합니다.
숫자 4 버튼을 누르면 숫자가 4씩 증가합니다.
숫자 5 버튼을 누르면 숫자가 5씩 증가합니다.

**제한 조건**
if는 사용할 수 있어도 else 사용하실 수 없습니다. GuardClauses 방법을 사용해주세요.
switch는 사용하실 수 없습니다.
let은 사용하실 수 없습니다. const만을 사용하여 문제를 해결해주세요.
함수 이름과 변수 이름에 줄임말은 사용하실 수 없습니다. 길더라도 명확하게 써주세요.
indent(인덴트, 들여쓰기) depth를 1로 유지해주세요. 예를 들어, for문 안에 if문이 있으면 indent depth는 2입니다. depth를 줄이는 좋은 방법은 함수(또는 메소드)를 분리하면 됩니다.

**요구사항**
- [ ] ESLint를 돌린 결과 아무런 문제가 없어야 합니다.
- [ ] 모든 인수 테스트를 통과시켜야 합니다.
- [ ] 한 파일에는 하나의 컴포넌트만 있어야 합니다.

**진행이슈**
- 자식 컴포넌트에서 부모로 데이터를 보내 어떤 버튼에서 눌렀는지에 따라 count의 state를 바꾸려고 하였고 데이터를 보내는 방법을 찾는 중입니다.

2020-09-23 16:42 UTC, hannut91 requested changes
굉장히 잘해주고 계십니다 ㅎㅎ 갑자기 코드가 좋아져서 걱정이긴한데 분명히 이해하고 진행하셨으면 좋겠고, 이해가 안되셨다면 이해가 될때까지 도움을 요청하셨으면 좋겠습니다

2020-09-23 16:42 UTC, hannut91 commented on src/components/Buttons.jsx
> +import Button from './Button';
리액트 라이브러리와 로컬 컴포넌트 임포트를 빈 줄로 구분해주면 좋을 것 같아요

2020-09-23 16:42 UTC, hannut91 commented on src/index.jsx
> +ReactDOM.render(<App />, document.getElementById('app'));
`index.jsx`에서 `render`하는 일과 `<App />`컴포넌트를 정의하는일 두 가지 일을 하고 있어요. 파일로 분리하여 이 두 가지 일을 분리할 수 있을까요?

2020-09-23 16:42 UTC, hannut91 commented on src/index.jsx
> +      return 0;
아무것도 반환하지 않는다는 것을 나타낼 때는 `return;`으로 표현합니다.

2020-09-23 16:42 UTC, hannut91 commented on src/components/Page.jsx
> +      />
이 부분을 만약에 만드신 `Button`컴포넌트로 구현할 수 있을까요?

2020-09-23 16:42 UTC, hannut91 commented on src/index.jsx
> +    return 0;
마지막 라인에는 반환하지 않는게 좋을 것 같아요

2020-09-23 16:42 UTC, hannut91 commented on src/index.jsx
> +  function handleClick(conditionValue) {
버튼을 클릭했을 때 조건에 따라서 다르게 처리해주신 것 같아요. CounterBtn 버튼을 클릭했을 때 파라미터로 1을 넘겨주게 되면 이 조건문이 아직도 필요할까요?

2020-09-24 10:20 UTC, comejtome508 commented on src/components/Buttons.jsx
> +import Button from './Button';
아하~! 구분하였습니다!

2020-09-24 13:07 UTC, comejtome508 commented on src/index.jsx
> +  function handleClick(conditionValue) {
네 CounterBtn에도 Buttons와 같이 함수로 매개변수에 1을 전달하게 하고 조건문을 제거했습니다!

2020-09-24 14:22 UTC, hannut91 commented on src/index.jsx
> +  function handleClick(conditionValue) {
코드 올려주시면 보겠습니다 ㅎㅎ

2020-09-24 15:22 UTC, comejtome508 commented on src/components/Page.jsx
> +      />
이 부분의 요구사항을 정확하게 이해하지 못했습니다 ㅜ

2020-09-24 15:23 UTC, hannut91 commented on src/components/Page.jsx
> +      />
`CounterButton` 대신에 `Button`을 이용해서 동일한 결과를 얻을 수 있을까요?

2020-09-24 16:26 UTC, comejtome508 commented on src/components/Page.jsx
> +      />
합쳐보았는데 버튼을 프린트하는 부분에서 Click me와 합쳐서 나오는 문제를 해결해야 합니다ㅜㅜ

2020-09-25 15:58 UTC, hannut91 requested changes

2020-09-25 15:58 UTC, hannut91 commented on src/components/App.jsx
> +  }
`conditionValue`는 어떤 것을 의미하나요? 매개변수를 count와 더한 후 count로 저장합니다. count와 더한다는 것은 무엇을 의미하나요? 단순히 `value`나 `number`로 해도 충분히 이해될 것 같아요.

2020-09-25 15:58 UTC, hannut91 commented on src/components/CounterBtn.jsx
> +export default function CounterBtn({ count, onClick }) {
버튼을 줄여서 `Btn`으로 사용하신 것 같아요. `Button`으로 쓰는게 더 명확하고 좋을 것 같습니다

2020-09-25 15:58 UTC, hannut91 commented on src/components/Page.jsx
> +      <Buttons count={count} onClick={onClick} />
둘이 사용하는게 거의 비슷해 보이네요. 어떤 차이가 있나요?

2020-09-25 15:58 UTC, hannut91 commented on src/components/Button.jsx
> +        {children}
`Click me`는 여기에 없는게 더 좋을 것 같아요. 그리고 onClick도 지금 1을 넘겨주고 있는데, 이 컴포넌트는 버튼을 클릭했을 때 UI이벤트를 넘겨주는 역할과 화면에 내용들을 보여주는 역할만 해야해요. UI이벤트를 처리해서 `1`이라는 값을 넘겨준다는 내용이 같이 들어있습니다. 

다음과 같이 버튼을 클릭하는 역할과 내용물을 보여주는 역할을 잘 분리하면

```js
export default function Button({ children, onClick }) {
  return (
    <button type="button" onClick={onClick}>
      {children}
    </button>
  );
}
```

다음과 같이 `사용`할 수 있습니다.

```js
<Button onClick={() => onClick(1)}>
  Click me! ({count})
</Button>

{[1, 2, 3, 4, 5].map((it) => (
  <Button key={it} onClick={() => onClick(it)}>{it}</Button>
))}
```

2021-01-17 12:56 UTC, merged