주석추가 및 버튼 클릭시 count1 증가
CodeSoom/week2-assignment-1 pull request #45
Opened 2020-09-22 16:00 UTC by hanamDeveloper

버튼 누를시 count  1증가
button 클릭시 count 1 증가.

2020-09-23 14:18 UTC, Kihyun92 requested changes
eslint가 적용이 안되어있는듯 하네요. 혹시 저장(컨트롤s / 커맨드s)나 `npx eslint --fix .`이 안먹나요? 이 부분은 해보시고 안되면 바로 말씀주세요~

다음 커밋에서는 이번 과제의 목표인 관심사분리가 적용돼있으면 좋겠네요~ 지금 구조를 잘 생각해보시면 컴포넌트를 잘 나눌 수 있으실거에요!

2020-09-23 14:18 UTC, Kihyun92 commented on src/index.jsx
> +    console.log(key);
Counter에서 key는 어떤것 때문에 받아오도록 하셨나요? 여기에서 필요한 값일까요?

2020-09-23 14:18 UTC, Kihyun92 commented on src/index.jsx
> +function Buttons( {count, onClick} ) {
버튼들에서 count 값을 노출해줘야하는 케이스가 있을까요~?

2020-09-23 14:18 UTC, Kihyun92 commented on src/index.jsx
> +    //일단 받아와보자
주석을 보니 막힌곳이 어딘지 알겠네요~ 가능하면 다음 커밋부터는 주석은 다 지우고, 주석에 적어둔 생각들을 PR에 적어주세요~ 👍 

지금 숫자를 1씩 더하는건 처리가 되어있지만, 버튼에 적힌 숫자만큼 더해주는 기능이 없는 상황이죠. 기존 함수에서 한번에 처리하기가 너무 복잡하다면, 숫자 버튼들을 위한 별도의 클릭 함수를 하나 추가해보는건 어떨까요?

2020-09-24 07:03 UTC, hanamDeveloper commented on src/index.jsx
> +    console.log(key);
앗.. 아뇨! 그 테스트하다가 안지워놨던거같아요 바로 수정하겠습니다!

2020-09-24 07:03 UTC, hanamDeveloper commented on src/index.jsx
> +function Buttons( {count, onClick} ) {
바로 수정하겠습니다!

2020-09-24 07:05 UTC, hanamDeveloper commented on src/index.jsx
> +    console.log(key);
네.. npx eslint --fix . 이게 안먹더라구요.. ㅠ 명령어 입력하면 자꾸 설치하고 적용이 안되고있어요

2020-09-24 14:26 UTC, Kihyun92 requested changes
index.js는 단순히 진입점입니다~ 여기서도 App 컴포넌트로 분리할 수 있지 않을까요?

이번 과제의 의도에 대해서 많은 고민을 해보신 것 같아요~ 좋습니다 👍

2020-09-24 14:26 UTC, Kihyun92 commented on src/index.jsx
> +  }
이 두 함수가 각각 어떤 역할을 하고 있나요? 하나로 합칠 수는 없을까요? 

그리고 이벤트 핸들러 네이밍은 `on~~={handle~~}`과 같이 간단하고 명확하게 역할을 알 수 있도록 컨벤션을 맞춰주면 좋을 것 같아요~
참고: https://medium.com/javascript-in-plain-english/handy-naming-conventions-for-event-handler-functions-props-in-react-fc1cbb791364

2020-09-24 15:48 UTC, hanamDeveloper commented on src/index.jsx
> +  }
넵 확인했습니다 감사합니다!

2020-09-25 12:14 UTC, Kihyun92 commented
> index.js는 단순히 진입점입니다~ 여기서도 App 컴포넌트로 분리할 수 있지 않을까요?

@hanamDeveloper 님, 위 내용 한번 확인 해주세요~

2020-09-25 12:17 UTC, Kihyun92 requested changes

2020-09-25 12:17 UTC, Kihyun92 commented on src/index.jsx
> +      onButtonClick={handleClick}
같은 함수를 굳이 다른 이름으로 넘길 필요가 있을까요? :)

2020-09-25 12:17 UTC, Kihyun92 commented on src/Page.jsx
> +        onButtonClick={onButtonClick}
네이밍에 Button이라고 명시해주지 않아도, click이 들어있으니 뭔가를 눌렀을때 실행되는 함수라는걸 알 수 있는 것 같아요~ 어떤가요?

2020-09-26 04:17 UTC, hanamDeveloper commented on src/Page.jsx
> +        onButtonClick={onButtonClick}
그치만.. onClick 과 onButtonClick 은 각각 역할이 달라서 이름을 다르게 쓰긴해야하는데 onButtonClick을 그렇다면 좀 더 정확하게 onNumberClick 이라고 명시하는게 좋을까요..?

2020-09-26 04:17 UTC, hanamDeveloper commented on src/index.jsx
> +      onButtonClick={handleClick}
앗.. 맞네요! 좀 더 꼼꼼하게 살펴보고 커밋하도록 하겠습니다 감사합니다!

2020-09-26 13:27 UTC, Kihyun92 approved these changes
좋습니다~ 처음에 작성한 코드와 지금 코드가 얼마나 변했는지 확인해보시면 좋을 것 같아요~ 👍

2020-10-05 12:57 UTC, merged