Try to make separate components
CodeSoom/week2-assignment-1 pull request #47
Opened 2020-09-24 13:16 UTC by onys-programmer

And AddCount from number buttons

Counter 컴포넌트 먼저 따로 떼어보려고 새 파일을 만들고

구글링으로 import, export 등을 찾아 적용해보았으나 구현 실패..

일단 한 파일에 만든 다음에 분리해야지 하며 과제 진행.

AddCount 컴포넌트를 만들어 숫자버튼에서 클릭을 감지하면 click me의 count에 add 시키려고 시도해보았으나 코드 전체의 흐름을 아직 파악하지 못해 어디서부터 어떻게 손대야할 지 모르겠음.

숫자버튼에서 listener로 클릭을 감지한다. 
GuardClauses로 숫자별 count에 add되는 값을 차등 적용한다.
새로 렌더링하게 만든다.

이런 계획이 머릿속에서 이루어졌는데 갈 길이 멉니다.. ^^ 무엇을 어떻게 공부해야할 지 feed forward 부탁드립니다..! 

git 사용법도 버벅이다가 10시를 넘어버렸네요.;. 통탄..

2020-09-24 14:53 UTC, hannut91 requested changes
export, import 때문에 하나의 파일로 되어 있군요 ㅎㅎ

https://ko.javascript.info/modules-intro

이 글을 통해서 모듈이란 무엇인가에 대해서 학습해보시면 좋을 것 같아요

2020-09-24 14:53 UTC, hannut91 commented on src/Counter.jsx
> +export default Counter;1
여기에 1이 들어가 있네요 ㅎㅎ 삭제하는 게 좋을 것 같습니다.

2020-09-25 00:24 UTC, onys-programmer commented on src/Counter.jsx
> +export default Counter;1
너무 감사합니다 선생님!! 힘을 얻어갑니다

2020-09-25 12:42 UTC, onys-programmer commented
일단 Click me!옆에 숫자만 카운트 되는 앱을 만들고 컴포넌트들을 각각 분리했습니다.

분리하고 나니 count와 onClick 인자의 흐름이 눈에 보여 정말 기분 좋고 신기했습니다.

그 흐름에 착안하여 digitButtons (1,2,3,4,5버튼)에 onClickListener를 만들어 setState()를 통해 Counter 컴포넌트의 count의 상태를 재정의 하려 했으나 

결과는 다음과 같았습니다. (클립보드에 복사된 이미지를 올리는데 잘 올라갈지 걱정이네요.)
![image](https://user-images.githubusercontent.com/65271951/94268300-ecf6a680-ff77-11ea-9930-340fc2b3a367.png)

2020-09-25 16:04 UTC, hannut91 requested changes
먼저 코드가 뒤죽박죽으로 정렬이 되어있어서 이해하기 어렵습니다. 편집기의 자동정렬 기능을 이용해서 먼저 잘 정리해주세요. 그러면 어디가 잘못되었는지 더 파악하기 쉬워지실거에요.

그리고 `eslint`를 실행하면 내가 작성한 코드를 점검할 수 있습니다. 그러면 내가 실수할 수 있는 부분을 미리 확인할 수 있습니다. 명령어로 `npm run lint`를 실행하여 잘못된 곳이 어디인지 확인해보세요.

2020-09-25 16:04 UTC, hannut91 commented on src/components/DigitClickListener.jsx
> +            onClick={onClick}
tag에 속성으로 넣어야 하는데 div태그의 텍스트로 적어주셨네요. 올바르게 사용하려면 

`<button onClick={onClick}></button>`

이런식으로 사용하셔야 됩니다.

2020-09-25 16:04 UTC, hannut91 commented on src/components/Button.jsx
> +);
`jsx`는 항상 하나의 태그로 감싸져 있어야 합니다. 예를들면

```js
return (
  <div>
    <button type="button">
      {children}
    </button>
    <DigitClickListener />
  </div>
);
```

이런식이 되어야 합니다.

```js
return (
  <div>Hello</div>
  <div>world</div>
);
```

이런식으로 최 상단에 2개 이상이 나란히 있을 수 없습니다.

2020-09-25 16:04 UTC, hannut91 commented on src/components/Button.jsx
> +        </button>,
여기에 `,`문자가 들어있네요

2020-09-26 15:54 UTC, hannut91 requested changes
`.eslintrc.js`는 수정하시면 안됩니다 ㅎㅎ 코드숨만의 규칙이 적용되어있는 것이라서요. 회사에서도 마찬가지로 적용된 룰을 함부로 바꿀 수는 없습니다.

코드를 올리기전에 eslint를 실행하여 점검해보시면 좋을 것 같습니다.

2020-09-27 11:41 UTC, onys-programmer commented
저는 수정한 기억이 없는데 고양이가 계속 키보드에 올라와서 저렇게 바뀌었나봅니다.. ㅠㅠ 많이 지워졌다는 표시죠? 명심하겠습니다. 어쩐지 eslint를 실행해도 별 변화가 없더라니.. 다음주부터는 eslint를 꼭 잘 실행해보겠습니다.

2021-01-17 12:56 UTC, merged